# Generated by Django 2.2.5 on 2019-09-27 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0010_auto_20190927_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarticle',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
