# Generated by Django 2.2.5 on 2019-09-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0011_auto_20190928_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userarticle',
            old_name='USER',
            new_name='user',
        ),
    ]
