# Generated by Django 2.2.5 on 2019-09-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0012_auto_20190928_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userarticle',
            name='user',
        ),
        migrations.AddField(
            model_name='userarticle',
            name='USER',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
