# Generated by Django 2.2.5 on 2019-09-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0015_auto_20190928_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userarticle',
            name='USER',
        ),
    ]
