# Generated by Django 2.2.5 on 2019-09-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0016_remove_userarticle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userarticle',
            name='USER',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
